[package]
name = "rust-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
actix-http = "3.2.2"
tera = "1.17.1"
mime = "0.3.16"
env_logger = "0.10.0"
log = "0.4.17"
anyhow = "1.0.65"
dotenv = "0.15.0"
serde = { version = "1.0.144", features = ["derive"] }